[package]
name = "dpc"
version = "0.1.0"
authors = ["widberg <https://github.com/widberg>"]
build = "build.rs"
edition = "2018"

[dependencies]
bimap = "0.6.1"
binwrite = "0.2.1"
built = { version = "0.4.4", features = ["git2"] }
clap = "2.33.3"
indicatif = "0.16.0"
nom = "6.1.2"
nom-derive = "0.8.0"
serde_json = "1.0"

[build-dependencies]
built = "0.4.4"
